backend:
  name: github
  repo: benmcgarvey/promo
  branch: main
  base_url: https://promo-dfh.pages.dev
publish_mode: editorial_workflow
media_folder: 'public/assets'

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'About Page'
        name: 'about'
        file: './src/pages/about.md'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Layout, name: layout, widget: hidden }
